name: Build And Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkout_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci
  build:
    runs-on: ubuntu-latest
    needs: checkout_and_build
    steps:
      - name: Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: checkout_and_build
    steps:
      - name: Test
        run: npm run test
